import { nullopt, opt, Optional } from "../core/optional";

enum Player {
  MCR = 0,
  UN = 1,
};
type PlayerMeta = {
  player: Player,
  name: string,
};
const players: PlayerMeta[] = [
  { player: Player.MCR, name: "MCR" },
  { player: Player.UN, name: "UN", },
];

enum Sector {
  Inner = 0,
  Belt = 1,
  Outer = 2,
};
type SectorMeta = {
  sector: Sector,
  name: string,
};
const sectors: SectorMeta[] = [
  { sector: Sector.Inner, name: "Inner Planets" },
  { sector: Sector.Belt, name: "The Belt" },
  { sector: Sector.Outer, name: "Outer Planets" },
]

enum Band {
  Inner = 0,
  Belt = 1,
  Jupiter = 2,
  Saturn = 3,
};
type BandMeta = {
  band: Band,
  name: string,
  sector: Sector,
};
const bands: BandMeta[] = [
  { band: Band.Inner, name: "Inner Planets", sector: Sector.Inner },
  { band: Band.Belt, name: "The Belt", sector: Sector.Belt },
  { band: Band.Jupiter, name: "Jupiter", sector: Sector.Outer },
  { band: Band.Saturn, name: "Saturn", sector: Sector.Outer },
];

enum Orbital {
  Earth = 0,
  Mars = 1,
  Ceres = 2,
  Tycho = 3,
  Eros = 4,
  Thoth = 5,
  Jupiter = 6,
  Saturn = 7,
};
type OrbitalMeta = {
  orbital: Orbital,
  name: string,
  band: Band,
};
const orbitals: OrbitalMeta[] = [
  { orbital: Orbital.Earth, name: "Earth", band: Band.Inner },
  { orbital: Orbital.Mars, name: "Mars", band: Band.Inner },
  { orbital: Orbital.Ceres, name: "Ceres", band: Band.Belt },
  { orbital: Orbital.Tycho, name: "Tycho", band: Band.Belt },
  { orbital: Orbital.Eros, name: "Eros", band: Band.Belt },
  { orbital: Orbital.Thoth, name: "Thoth", band: Band.Belt },
  { orbital: Orbital.Jupiter, name: "Jupiter", band: Band.Jupiter },
  { orbital: Orbital.Saturn, name: "Saturn", band: Band.Saturn },
];

enum Base {
  Eurasia = 0,
  Africa = 1,
  MarinerValley = 2,
  LondresNova = 3,
  Ceres = 4,
  Tycho = 5,
  Eros = 6,
  Thoth = 7,
  Europa = 8,
  Ganymede = 9,
  Rhea = 10,
  Titan = 11,
};
type BaseMeta = {
  base: Base,
  name: string,
  orbital: Orbital,
};
const bases: BaseMeta[] = [
  { base: Base.Eurasia, name: "Eurasia", orbital: Orbital.Earth },
  { base: Base.Africa, name: "Africa", orbital: Orbital.Earth },
  { base: Base.MarinerValley, name: "Mariner Valley", orbital: Orbital.Mars },
  { base: Base.LondresNova, name: "Londres Nova", orbital: Orbital.Mars },
  { base: Base.Ceres, name: "Ceres", orbital: Orbital.Ceres },
  { base: Base.Tycho, name: "Tycho", orbital: Orbital.Tycho },
  { base: Base.Eros, name: "Eros", orbital: Orbital.Eros },
  { base: Base.Thoth, name: "Thoth", orbital: Orbital.Thoth },
  { base: Base.Europa, name: "Europa", orbital: Orbital.Jupiter },
  { base: Base.Ganymede, name: "Ganymede", orbital: Orbital.Jupiter },
  { base: Base.Rhea, name: "Rhea", orbital: Orbital.Saturn },
  { base: Base.Titan, name: "Titan", orbital: Orbital.Saturn },
];

enum Event {
  Drummer = 0,
  Miller = 1,
  Cotyar = 2,
  MaoKwik = 3,
  Assassin = 4,
  CovertOp = 5,
  BushNaval = 6,
  AntonyDresden = 7,
  FranklinDeGraff = 8,
  Terraforming = 9,
  VoicesEros = 10,
  DestructionDeimos = 11,
  BlockadeEarth = 12,
  BlockadeMars = 13,
  SadavirErrinwright = 14,
  Slingshot = 15,
  BlackOps = 16,
  JulieMao = 17,
  StarHelix = 18,
  RiotGear = 19,
  TheHybrid = 20,
  Nauvoo = 21,
  TheresaYao = 22,
  BobbieDraper = 23,
  Ambush = 24,
  CaptainYvgeny = 25,
  StealthShips = 26,
  HeavyBurn = 27,
  Razorback = 28,
  AdmiralSouther = 29,
};
type EventMeta = {
  event: Event,
  title: string,
  subtitle: Optional<string>,
  text: string,
  ap: 2 | 3 | 4,
  factions: [boolean, boolean],
  modelImplemented: boolean,
};
const events: EventMeta[] = [
  {
    event: Event.Drummer,
    title: "Inspiring Leader",
    subtitle: opt("Camina Drummer"),
    text: "Perform 1 AP.",
    ap: 3,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.Miller,
    title: "Discreet Detective",
    subtitle: opt("Josephus Miller"),
    text: "Keep this card at no CP cost. Discard to first perform the AP, then the eligible Event on an Action card on your turn.",
    ap: 4,
    factions: [false, true],
    modelImplemented: false,
  },
  {
    event: Event.Cotyar,
    title: "First-rate Spy",
    subtitle: opt("Cotyar Ghazi"),
    text: "Keep this card at no CP cost. If you play this as your Event during Scoring, look at the Bonus token and take 2 AP of Actions.",
    ap: 4,
    factions: [false, true],
    modelImplemented: false,
  },
  {
    event: Event.MaoKwik,
    title: "Corporate Connections",
    subtitle: opt("Mao-Kwikowski Mercantile"),
    text: "Keep this card at no CP cost. Discard to treat the AP number on any Action Card as 4 AP.",
    ap: 3,
    factions: [true, true],
    modelImplemented: false,
  },
  {
    event: Event.Assassin,
    title: "Assassin",
    subtitle: nullopt,
    text: "Both players must discard one Kept card.",
    ap: 2,
    factions: [true, false],
    modelImplemented: false,
  },
  {
    event: Event.CovertOp,
    title: "Covert Op",
    subtitle: nullopt,
    text: "Exchange the position of two influence, one belonging to each player.",
    ap: 3,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.BushNaval,
    title: "Industrial Contractor",
    subtitle: opt("Bush Naval Shipyards"),
    text: "All players build all fleets. Gain 1 CP if your opponent built a fleet.",
    ap: 4,
    factions: [false, true],
    modelImplemented: true,
  },
  {
    event: Event.AntonyDresden,
    title: "Unscrupulous Scientist",
    subtitle: opt("Antony Dresden"),
    text: "Place influence on each technology base: Londres Nova, Tycho, and Thoth.",
    ap: 4,
    factions: [false, true],
    modelImplemented: true,
  },
  {
    event: Event.FranklinDeGraff,
    title: "Manipulable Ambassador",
    subtitle: opt("Franklin DeGraff"),
    text: "Place influence on each Earth base.",
    ap: 3,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.Terraforming,
    title: "Terraforming",
    subtitle: nullopt,
    text: "Place influence in each Mars base.",
    ap: 2,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.VoicesEros,
    title: "Historical Lessons",
    subtitle: opt("Voices of Eros"),
    text: "Place 1 influence in 1 Base each of the Inner Planets, Belt, and Outer Planets.",
    ap: 4,
    factions: [true, true],
    modelImplemented: true,
  },
  {
    event: Event.DestructionDeimos,
    title: "Destruction of Deimos",
    subtitle: nullopt,
    text: "Must remove 1 influence from each Mars base. Place 1 influence on an Earth base.",
    ap: 4,
    factions: [false, true],
    modelImplemented: true,
  },
  {
    event: Event.BlockadeEarth,
    title: "Blockade of Earth",
    subtitle: nullopt,
    text: "Place influence on an Earth base. If you have Orbital Control of Earth, you may also remove influence from an Earth base.",
    ap: 3,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.BlockadeMars,
    title: "Blockade of Mars",
    subtitle: nullopt,
    text: "Place influence on a Mars base. If you have Orbital Control of Mars, you may also remove influence from a Mars base.",
    ap: 3,
    factions: [false, true],
    modelImplemented: true,
  },
  {
    event: Event.SadavirErrinwright,
    title: "Executive Control",
    subtitle: opt("Sadavir Errinwright"),
    text: "On each Base where a player has 3 or more influence, they must remove 1.",
    ap: 4,
    factions: [false, true],
    modelImplemented: true,
  },
  {
    event: Event.Slingshot,
    title: "Civilian Risk-taking",
    subtitle: opt("Slingshot Racing"),
    text: "Remove 1 influence from any Outer Planets Base.",
    ap: 2,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.BlackOps,
    title: "Black Ops Team",
    subtitle: nullopt,
    text: "Remove 1 influence from up to 3 bases, each in a different Band.",
    ap: 4,
    factions: [true, true],
    modelImplemented: true,
  },
  {
    event: Event.JulieMao,
    title: "Retaliation",
    subtitle: opt("Julie Mao"),
    text: "Remove 1 influence on 2 Bases with the same Resource type.",
    ap: 4,
    factions: [true, true],
    modelImplemented: true,
  },
  {
    event: Event.StarHelix,
    title: "Security Forces",
    subtitle: opt("Star Helix"),
    text: "Remove up to 2 influence total from Bases where you have influence.",
    ap: 3,
    factions: [true, true],
    modelImplemented: true,
  },
  {
    event: Event.RiotGear,
    title: "Riots",
    subtitle: nullopt,
    text: "Remove up to 2 influence total on Belt Bases, no more than 1 per Base.",
    ap: 3,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.TheHybrid,
    title: "Bioweapon",
    subtitle: opt("The Hybrid"),
    text: "Select a Base. Draw the top card from the deck. Remove influence equal to the AP. If a Score card, remove all influence. Put card back on top of deck.",
    ap: 4,
    factions: [true, true],
    modelImplemented: false,
  },
  {
    event: Event.Nauvoo,
    title: "Moral Rejection",
    subtitle: opt("Nauvoo"),
    text: "Remove 1 influence or 1 fleet from anywhere.",
    ap: 2,
    factions: [true, true],
    modelImplemented: true,
  },
  {
    event: Event.TheresaYao,
    title: "Aggressive Captain",
    subtitle: opt("Theresa Yao"),
    text: "Remove X of your fleets from an Orbital. Remove X+1 opponent fleets (total) from that Orbital. X may be zero.",
    ap: 3,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.BobbieDraper,
    title: "Marine Strike Force",
    subtitle: opt("Bobbie Draper"),
    text: "Remove one opposing fleet, and place one of your fleets in the same Orbital (either unbuilt, or from another Orbital).",
    ap: 4,
    factions: [true, true],
    modelImplemented: true,
  },
  {
    event: Event.Ambush,
    title: "Ambush",
    subtitle: nullopt,
    text: "Remove an opposing fleet. Optionally, also remove one of your fleets from the same orbital.",
    ap: 3,
    factions: [true, false],
    modelImplemented: true,
  },
  {
    event: Event.CaptainYvgeny,
    title: "Reliable Captain",
    subtitle: opt("Colin Yvgeny"),
    text: "Remove 1 opponent fleet from an Orbital where you have a fleet.",
    ap: 2,
    factions: [false, true],
    modelImplemented: true,
  },
  {
    event: Event.StealthShips,
    title: "Stealth Ships",
    subtitle: nullopt,
    text: "Move a fleet up to 1 band, then remove it to remove up to 2 opposing fleets in the same Orbital.",
    ap: 3,
    factions: [false, true],
    modelImplemented: true,
  },
  {
    event: Event.HeavyBurn,
    title: "Heavy Burn",
    subtitle: nullopt,
    text: "Move up to two fleet groups up to two Bands each.",
    ap: 3,
    factions: [true, true],
    modelImplemented: false,
  },
  {
    event: Event.Razorback,
    title: "Optimized Design",
    subtitle: opt("Razorback"),
    text: "Move 1 fleet to any Orbital.",
    ap: 2,
    factions: [false, true],
    modelImplemented: true,
  },
  {
    event: Event.AdmiralSouther,
    title: "Admiral Initiative",
    subtitle: opt("Michael Souther"),
    text: "You may move each of your fleets up to one band.",
    ap: 4,
    factions: [true, true],
    modelImplemented: false,
  },
];


